# -*- coding: utf-8 -*-
from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


@dataclass(frozen=True)
class MonthlyReportResult:
    filename: str
    abs_path: str


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_header_footer(page_total=page_total)
            super().showPage()
        super().save()

    def _draw_page_header_footer(self, *, page_total: int) -> None:
        width, height = A4
        page_no = self._pageNumber

        self.setFillColor(colors.black)
        self.setFont("Helvetica-Oblique", 7)
        self.drawRightString(width - 40, height - 30, "OmniRiskDB by Arbo Security")

        self.setFont("Helvetica", 8)
        self.drawRightString(width - 40, 28, f"Page {page_no} / {page_total}")

        self.setFont("Helvetica-Bold", 20)
        self.drawCentredString(width / 2, height - 85, "Monthly Domain Analysis Report")

        self.setLineWidth(1)
        self.setStrokeColor(colors.lightgrey)
        self.line(40, height - 108, width - 40, height - 108)

        self.setFillColor(colors.black)
        self.setFont("Helvetica-Oblique", 8)
        self.drawString(40, 55, "Generated by DBVulScan - Monthly Domain Analysis")


SECTION_GAP = 28
TABLE_BOTTOM_MARGIN = 78


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _ensure_report_dir() -> Path:
    report_dir = _project_root() / "report_dir"
    report_dir.mkdir(parents=True, exist_ok=True)
    return report_dir


def _make_sequence() -> str:
    return f"{random.randint(10000, 99999)}"


def _format_pct(value) -> str:
    if value is None or value == "":
        return "-"

    if isinstance(value, Decimal):
        value = float(value)

    try:
        return f"{float(value):.2f}%"
    except (TypeError, ValueError):
        return "-"


def _format_count(value) -> str:
    try:
        return str(int(value or 0))
    except (TypeError, ValueError):
        return "0"


def _format_text(value) -> str:
    value = str(value or "").strip()
    return value if value else "-"


def _trim_text(c: canvas.Canvas, text: str, max_width: float, font_name: str, font_size: float) -> str:
    text = str(text or "")
    if c.stringWidth(text, font_name, font_size) <= max_width:
        return text

    ellipsis = "..."
    allowed = text
    while allowed and c.stringWidth(allowed + ellipsis, font_name, font_size) > max_width:
        allowed = allowed[:-1]
    return (allowed + ellipsis) if allowed else ellipsis


def _draw_domain_info_box(
    c: canvas.Canvas,
    *,
    domain_id: str,
    domain_name: str,
    start_date: str,
    end_date: str,
    width: float,
    height: float,
) -> float:
    c.setStrokeColor(colors.black)
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, height - 145, "Domain Info")

    box_x = 40
    box_y_top = height - 160
    box_w = width - 80
    box_h = 115

    c.setLineWidth(1)
    c.setStrokeColor(colors.lightgrey)
    c.rect(box_x, box_y_top - box_h, box_w, box_h, stroke=1, fill=0)

    label_x = box_x + 18
    colon_x = box_x + 175
    value_x = box_x + 190

    y = box_y_top - 22
    line_gap = 16

    c.setFont("Helvetica-Bold", 9)
    c.drawString(label_x, y, "Domain")
    c.setFont("Helvetica", 9)
    c.drawString(colon_x, y, ":")
    c.drawString(value_x, y, f"{domain_name} (ID={domain_id})")

    y -= line_gap
    c.setFont("Helvetica-Bold", 9)
    c.drawString(label_x, y, "Report Execution Date")
    c.setFont("Helvetica", 9)
    c.drawString(colon_x, y, ":")
    c.drawString(value_x, y, datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

    y -= line_gap
    c.setFont("Helvetica-Bold", 9)
    c.drawString(label_x, y, "Start Date")
    c.setFont("Helvetica", 9)
    c.drawString(colon_x, y, ":")
    c.drawString(value_x, y, str(start_date))

    y -= line_gap
    c.setFont("Helvetica-Bold", 9)
    c.drawString(label_x, y, "End Date")
    c.setFont("Helvetica", 9)
    c.drawString(colon_x, y, ":")
    c.drawString(value_x, y, str(end_date))

    return box_y_top - box_h


def _draw_assessment_statistics_table(
    c: canvas.Canvas,
    *,
    x: float,
    y_top: float,
    width: float,
    values: dict,
    as_of_date: str | None = None,
) -> float:
    header_h = 44
    row_h = 24

    rows = [
        ("The Number of Security Assessment Tests with Errors", int(values.get("tests_with_errors", 0))),
        ("The Number of Security Assessments with Errors", int(values.get("assessments_with_errors", 0))),
        ("The number of Security Assessment Tests", int(values.get("total_tests", 0))),
        ("The number of Security Assessments", int(values.get("total_assessments", 0))),
    ]

    table_h = header_h + (len(rows) * row_h)

    c.setLineWidth(1)
    c.setStrokeColor(colors.lightgrey)
    c.rect(x, y_top - table_h, width, table_h, stroke=1, fill=0)

    c.setFillColor(colors.whitesmoke)
    c.rect(x, y_top - header_h, width, header_h, stroke=0, fill=1)

    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(x + width / 2, y_top - 18, "Assessment Statistics")

    if as_of_date:
        c.setFont("Helvetica", 9)
        c.drawCentredString(x + width / 2, y_top - 34, f"As of End Date ({as_of_date})")

    value_col_w = 70
    label_col_w = width - value_col_w

    c.setStrokeColor(colors.lightgrey)
    c.setLineWidth(1)
    c.line(x + label_col_w, y_top - header_h, x + label_col_w, y_top - table_h)

    y = y_top - header_h
    for i, (label, val) in enumerate(rows):
        c.setFillColor(colors.white if i % 2 == 0 else colors.HexColor("#f3f4f6"))
        c.rect(x, y - row_h, width, row_h, stroke=0, fill=1)

        c.setStrokeColor(colors.lightgrey)
        c.line(x, y, x + width, y)

        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(x + 10, y - 16, label)
        c.drawRightString(x + width - 10, y - 16, str(val))

        y -= row_h

    return y_top - table_h


def _draw_distribution_of_tests_by_importance_grouped(
    c: canvas.Canvas,
    *,
    x: float,
    y_top: float,
    width: float,
    start_values: dict,
    end_values: dict,
    start_date: str,
    end_date: str,
) -> float:
    def _v(d: dict, k: str) -> int:
        return int((d or {}).get(k, 0) or 0)

    labels = ["CRITICAL", "MAJOR", "MINOR"]
    keys = ["critical", "major", "minor"]

    start_data = [_v(start_values, k) for k in keys]
    end_data = [_v(end_values, k) for k in keys]

    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y_top, "Distribution of Tests by Importance")

    chart_top = y_top - 20
    chart_h = 150
    chart_bottom = chart_top - chart_h

    c.setStrokeColor(colors.lightgrey)
    c.setLineWidth(1)
    c.line(x, chart_bottom, x + width, chart_bottom)
    c.line(x, chart_bottom, x, chart_top)

    max_val = max(start_data + end_data) if max(start_data + end_data) > 0 else 1

    c.saveState()
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 9)
    c.translate(x + 18, (chart_bottom + chart_top) / 2)
    c.rotate(90)
    c.drawCentredString(0, 0, "The number of Failed Tests")
    c.restoreState()

    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(x + width / 2, chart_bottom - 28, "Importance of Tests")

    left_pad = 70
    right_pad = 20
    usable_w = width - left_pad - right_pad
    group_w = usable_w / 3
    bar_w = 28
    inner_gap = 10

    for i in range(3):
        gx = x + left_pad + i * group_w + (group_w - (2 * bar_w + inner_gap)) / 2

        sv = start_data[i]
        sh = (sv / max_val) * (chart_h - 10)
        c.setFillColor(colors.HexColor("#3b82b6"))
        c.rect(gx, chart_bottom, bar_w, sh, stroke=0, fill=1)

        ev = end_data[i]
        eh = (ev / max_val) * (chart_h - 10)
        c.setFillColor(colors.HexColor("#10b981"))
        c.rect(gx + bar_w + inner_gap, chart_bottom, bar_w, eh, stroke=0, fill=1)

        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 9)
        c.drawCentredString(gx + bar_w / 2, chart_bottom + sh + 6, str(sv))
        c.drawCentredString(gx + bar_w + inner_gap + bar_w / 2, chart_bottom + eh + 6, str(ev))
        c.drawCentredString(x + left_pad + i * group_w + group_w / 2, chart_bottom - 12, labels[i])

    legend_y = chart_bottom - 60
    legend_x = x + (width / 2) - 110

    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#3b82b6"))
    c.rect(legend_x, legend_y, 10, 10, stroke=0, fill=1)
    c.setFillColor(colors.black)
    c.drawString(legend_x + 14, legend_y + 1, f"Start Date ({start_date})")

    c.setFillColor(colors.HexColor("#10b981"))
    c.rect(legend_x + 140, legend_y, 10, 10, stroke=0, fill=1)
    c.setFillColor(colors.black)
    c.drawString(legend_x + 154, legend_y + 1, f"End Date ({end_date})")

    caption_y = legend_y - 16
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 8)
    c.drawString(
        x,
        caption_y,
        "This distribution compares failed tests by severity for the selected domain on the start and end dates.",
    )

    return caption_y - 8


def _draw_three_column_table(
    c: canvas.Canvas,
    *,
    title: str,
    subtitle: str,
    first_column_label: str,
    first_column_key: str,
    second_column_label: str,
    second_column_key: str,
    third_column_label: str,
    third_column_key: str,
    rows: list[dict],
    width: float,
    height: float,
    empty_message: str,
    formatter,
) -> None:
    section_title_y = height - 135
    table_x = 40
    table_w = width - 80
    header_h = 30
    row_h = 24
    first_page_top = section_title_y - 16
    next_page_top = height - 170

    name_col_w = 290
    value_col_w = (table_w - name_col_w) / 2

    def _draw_section_header(y_top: float) -> float:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(table_x, y_top, title)

        c.setFont("Helvetica", 9)
        c.drawString(table_x + 165, y_top, subtitle)

        table_top = y_top - 14
        c.setFillColor(colors.whitesmoke)
        c.setStrokeColor(colors.lightgrey)
        c.rect(table_x, table_top - header_h, table_w, header_h, stroke=1, fill=1)

        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(table_x + 10, table_top - 19, first_column_label)
        c.drawCentredString(table_x + name_col_w + value_col_w / 2, table_top - 19, second_column_label)
        c.drawCentredString(table_x + name_col_w + value_col_w + value_col_w / 2, table_top - 19, third_column_label)

        c.line(table_x + name_col_w, table_top, table_x + name_col_w, table_top - header_h)
        c.line(
            table_x + name_col_w + value_col_w,
            table_top,
            table_x + name_col_w + value_col_w,
            table_top - header_h,
        )
        return table_top - header_h

    current_bottom = _draw_section_header(first_page_top)

    if not rows:
        c.setStrokeColor(colors.lightgrey)
        c.setFillColor(colors.white)
        c.rect(table_x, current_bottom - row_h, table_w, row_h, stroke=1, fill=1)
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 9)
        c.drawString(table_x + 10, current_bottom - 16, empty_message)
        return

    for index, row in enumerate(rows):
        next_row_bottom = current_bottom - row_h
        if next_row_bottom < TABLE_BOTTOM_MARGIN:
            c.showPage()
            current_bottom = _draw_section_header(next_page_top)
            next_row_bottom = current_bottom - row_h

        c.setFillColor(colors.white if index % 2 == 0 else colors.HexColor("#f8fafc"))
        c.setStrokeColor(colors.lightgrey)
        c.rect(table_x, current_bottom - row_h, table_w, row_h, stroke=1, fill=1)
        c.line(table_x + name_col_w, current_bottom, table_x + name_col_w, current_bottom - row_h)
        c.line(
            table_x + name_col_w + value_col_w,
            current_bottom,
            table_x + name_col_w + value_col_w,
            current_bottom - row_h,
        )

        c.setFillColor(colors.black)
        c.setFont("Helvetica", 9)
        name_text = _trim_text(c, row.get(first_column_key, ""), name_col_w - 16, "Helvetica", 9)
        c.drawString(table_x + 8, current_bottom - 16, name_text)
        c.drawCentredString(
            table_x + name_col_w + value_col_w / 2,
            current_bottom - 16,
            formatter(row.get(second_column_key)),
        )
        c.drawCentredString(
            table_x + name_col_w + value_col_w + value_col_w / 2,
            current_bottom - 16,
            formatter(row.get(third_column_key)),
        )

        current_bottom = next_row_bottom


def _draw_database_security_score_table(c: canvas.Canvas, *, rows: list[dict], start_date: str, end_date: str, width: float, height: float) -> None:
    _draw_three_column_table(
        c,
        title="Database Security Score",
        subtitle="Successful Test Percent",
        first_column_label="Assessment Name",
        first_column_key="assessment_name",
        second_column_label=f"Start Date ({start_date})",
        second_column_key="start_success_pct",
        third_column_label=f"End Date ({end_date})",
        third_column_key="end_success_pct",
        rows=rows,
        width=width,
        height=height,
        empty_message="No assessment run data found for the selected dates.",
        formatter=_format_pct,
    )


def _draw_failed_critical_tests_table(c: canvas.Canvas, *, rows: list[dict], start_date: str, end_date: str, width: float, height: float) -> None:
    _draw_three_column_table(
        c,
        title="The Number of Failed Critical Tests",
        subtitle="",
        first_column_label="Checkpoint Name",
        first_column_key="checkpoint_name",
        second_column_label=f"Start Date ({start_date})",
        second_column_key="start_fail_count",
        third_column_label=f"End Date ({end_date})",
        third_column_key="end_fail_count",
        rows=rows,
        width=width,
        height=height,
        empty_message="No failed critical checkpoint data found for the selected dates.",
        formatter=_format_count,
    )


def _draw_failed_critical_tests_by_assessment_table(c: canvas.Canvas, *, rows: list[dict], start_date: str, end_date: str, width: float, height: float) -> None:
    _draw_three_column_table(
        c,
        title="The Number of Critical Failed Tests by Assessments",
        subtitle="",
        first_column_label="Assessment Name",
        first_column_key="assessment_name",
        second_column_label=f"Start Date ({start_date})",
        second_column_key="start_fail_count",
        third_column_label=f"End Date ({end_date})",
        third_column_key="end_fail_count",
        rows=rows,
        width=width,
        height=height,
        empty_message="No critical failed test data by assessment found for the selected dates.",
        formatter=_format_count,
    )


def _draw_five_column_table(
    c: canvas.Canvas,
    *,
    title: str,
    rows: list[dict],
    columns: list[dict],
    width: float,
    height: float,
    empty_message: str,
) -> None:
    section_title_y = height - 135
    table_x = 30
    table_w = width - 60
    header_h = 32
    row_h = 24
    first_page_top = section_title_y - 16
    next_page_top = height - 170

    col_widths = [150, 150, 62, 68, 85]

    def _draw_section_header(y_top: float) -> float:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(table_x, y_top, title)

        table_top = y_top - 14
        c.setFillColor(colors.whitesmoke)
        c.setStrokeColor(colors.lightgrey)
        c.rect(table_x, table_top - header_h, table_w, header_h, stroke=1, fill=1)

        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 8)
        x_cursor = table_x
        for index, column in enumerate(columns):
            text_x = x_cursor + 6
            c.drawString(text_x, table_top - 20, column["label"])
            x_cursor += col_widths[index]
            if index < len(columns) - 1:
                c.line(x_cursor, table_top, x_cursor, table_top - header_h)

        return table_top - header_h

    current_bottom = _draw_section_header(first_page_top)

    if not rows:
        c.setStrokeColor(colors.lightgrey)
        c.setFillColor(colors.white)
        c.rect(table_x, current_bottom - row_h, table_w, row_h, stroke=1, fill=1)
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 9)
        c.drawString(table_x + 10, current_bottom - 16, empty_message)
        return

    for index, row in enumerate(rows):
        next_row_bottom = current_bottom - row_h
        if next_row_bottom < TABLE_BOTTOM_MARGIN:
            c.showPage()
            current_bottom = _draw_section_header(next_page_top)
            next_row_bottom = current_bottom - row_h

        c.setFillColor(colors.white if index % 2 == 0 else colors.HexColor("#f8fafc"))
        c.setStrokeColor(colors.lightgrey)
        c.rect(table_x, current_bottom - row_h, table_w, row_h, stroke=1, fill=1)

        x_cursor = table_x
        for i in range(len(columns) - 1):
            x_cursor += col_widths[i]
            c.line(x_cursor, current_bottom, x_cursor, current_bottom - row_h)

        c.setFillColor(colors.black)
        c.setFont("Helvetica", 8)
        x_cursor = table_x
        for i, column in enumerate(columns):
            raw_value = row.get(column["key"], "")
            value = column["formatter"](raw_value)
            text = _trim_text(c, value, col_widths[i] - 10, "Helvetica", 8)
            c.drawString(x_cursor + 5, current_bottom - 16, text)
            x_cursor += col_widths[i]

        current_bottom = next_row_bottom


def _draw_vulnerability_assessment_changes_table(c: canvas.Canvas, *, rows: list[dict], width: float, height: float) -> None:
    _draw_five_column_table(
        c,
        title="Changes in vulnerability Assessments",
        rows=rows,
        columns=[
            {"label": "Assessment Name", "key": "assessment_name", "formatter": _format_text},
            {"label": "Checkpoint Name", "key": "checkpoint_name", "formatter": _format_text},
            {"label": "Severity", "key": "checkpoint_severity", "formatter": _format_text},
            {"label": "Category", "key": "checkpoint_category", "formatter": _format_text},
            {"label": "Result Change", "key": "result_change", "formatter": _format_text},
        ],
        width=width,
        height=height,
        empty_message="No vulnerability assessment changes found for the selected dates.",
    )


def generate_monthly_domain_analysis_pdf(
    *,
    domain_id: str,
    domain_name: str,
    start_date: str,
    end_date: str,
    stats: dict | None = None,
    severity_dist_start: dict | None = None,
    severity_dist_end: dict | None = None,
    assessment_score_rows: list[dict] | None = None,
    failed_critical_checkpoint_rows: list[dict] | None = None,
    failed_critical_tests_by_assessment_rows: list[dict] | None = None,
    vulnerability_assessment_change_rows: list[dict] | None = None,
) -> MonthlyReportResult:
    if stats is None:
        stats = {}
    if severity_dist_start is None:
        severity_dist_start = {}
    if severity_dist_end is None:
        severity_dist_end = {}
    if assessment_score_rows is None:
        assessment_score_rows = []
    if failed_critical_checkpoint_rows is None:
        failed_critical_checkpoint_rows = []
    if failed_critical_tests_by_assessment_rows is None:
        failed_critical_tests_by_assessment_rows = []
    if vulnerability_assessment_change_rows is None:
        vulnerability_assessment_change_rows = []

    report_dir = _ensure_report_dir()
    seq = _make_sequence()
    filename = f"monthly_analysis_{domain_id}_{seq}.pdf"
    out_path = report_dir / filename

    c = NumberedCanvas(str(out_path), pagesize=A4)
    width, height = A4

    domain_bottom_y = _draw_domain_info_box(
        c,
        domain_id=domain_id,
        domain_name=domain_name,
        start_date=start_date,
        end_date=end_date,
        width=width,
        height=height,
    )

    stats_table_y_top = domain_bottom_y - 25
    stats_bottom_y = _draw_assessment_statistics_table(
        c,
        x=40,
        y_top=stats_table_y_top,
        width=width - 80,
        values=stats,
        as_of_date=str(end_date),
    )

    chart_y_top = stats_bottom_y - 35
    chart_bottom_y = _draw_distribution_of_tests_by_importance_grouped(
        c,
        x=40,
        y_top=chart_y_top,
        width=width - 80,
        start_values=severity_dist_start,
        end_values=severity_dist_end,
        start_date=str(start_date),
        end_date=str(end_date),
    )

    if chart_bottom_y - SECTION_GAP < 170:
        c.showPage()
    _draw_database_security_score_table(
        c,
        rows=assessment_score_rows,
        start_date=str(start_date),
        end_date=str(end_date),
        width=width,
        height=height,
    )

    c.showPage()
    _draw_failed_critical_tests_table(
        c,
        rows=failed_critical_checkpoint_rows,
        start_date=str(start_date),
        end_date=str(end_date),
        width=width,
        height=height,
    )

    c.showPage()
    _draw_failed_critical_tests_by_assessment_table(
        c,
        rows=failed_critical_tests_by_assessment_rows,
        start_date=str(start_date),
        end_date=str(end_date),
        width=width,
        height=height,
    )

    c.showPage()
    _draw_vulnerability_assessment_changes_table(
        c,
        rows=vulnerability_assessment_change_rows,
        width=width,
        height=height,
    )

    c.showPage()
    c.save()

    return MonthlyReportResult(filename=filename, abs_path=str(out_path))
